name: Caliper test
version: "2.0.0"
caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: false

channels:
  - channelName: channel1
    contracts:
      - id: chaincode1
        contractID: KVContract
        name: chaincode1
        intsall:
          version: v0
          path: ../../chaincodes/chaincode-kv-node
          language: node



organizations:
    - mspid: HomeApplianceMSP
      peers:
        - peer0.homeappliance.amrita.edu
      certificateAuthorities:
      - ca.homeappliance.amrita.edu
      adminPrivateKey:
        path: "../fablo-target/fabric-config/crypto-config/peerOrganizations/homeappliance.amrita.edu/users/Admin@homeappliance.amrita.edu/msp/keystore/priv-key.pem"
      signedCert:
        path: "../fablo-target/fabric-config/crypto-config/peerOrganizations/homeappliance.amrita.edu/users/Admin@homeappliance.amrita.edu/msp/signcerts/Admin@homeappliance.amrita.edu-cert.pem"
      identities:
        certificates:
          - name: "Admin"
            clientPrivateKey: 
              path: "../fablo-target/fabric-config/crypto-config/peerOrganizations/homeappliance.amrita.edu/users/Admin@homeappliance.amrita.edu/tls/client.key"
            clientSignedCert:
              path: "../fablo-target/fabric-config/crypto-config/peerOrganizations/homeappliance.amrita.edu/users/Admin@homeappliance.amrita.edu/tls/client.crt"
      connectionProfile:
        path: "../fablo-target/fabric-config/connection-profiles/connection-profile-homeappliance.yaml"
        discover: true